spring:
  redis:
    database: 4
    host: localhost
    port: 6379
    password:
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0